class AppConstants:
    error = "error"
    id = "id"
    name = "name"
    username = "username"
    password = "password"
    token = "token"
    authorization = "authorization"
    message = "message"
    success = "success"
    title = "title"
    content = "content"
    user_id = "user_id"
    posts = "posts"
